### ISSUE TITLE
Find dialog freezes the app

### ISSUE THREAD

**Issue by zadam** [TheoXiong/electron-find#1]
Hello, I'm trying out your component with example code:

```javascript
const { remote, ipcRenderer } = require('electron');
const { FindInPage } = require('electron-find');

let findInPage = new FindInPage(remote.getCurrentWebContents());
findInPage.openFindWindow();
```

It opens the dialog nicely, and I start to enter search term, but after a second it turns into these dots (e.g. "•••") and the app is completely frozen (has to be killed).

Any idea what might be wrong? I'm using electron 4.0.3

Thanks.

**Comment by TheoXiong** [comment]
Hello, I test it again with electron 4.0.3 on windows 10, it is also work well. 
What's your platform? 

otherwise,  have you tried the example in this project with run  "npm run e" ?

**Comment by zadam** [comment]
Hello, I managed to track the problem down to the fact I had a webview in my page. After I removed it my app didn't crash anymore. Not sure what the underlying reason behind this is. 

Anyway, I got it working and it's great. Thanks for your work!

**Comment by Sryther** [comment]
I have the same issue today but I want to use electron-find within my webviews. What can I do?
I'm using electron 7.1.1.

**Comment by xudafeng** [comment]
@Sryther 

I met the same issue, my electron version is 7.1.1, did you solve it?

**Comment by Sryther** [comment]
@xudafeng I forked the repo and made some changes but it's not stable at all... It's still crashing in some conditions. It's really ugly code but I'm using it for a personal project so it's okay for me.
Here is the repo: https://github.com/Sryther/electron-find

**Comment by Sryther** [comment]
This issue is related to electron/electron#20602.

**Comment by Sryther** [comment]
You can avoid the issue by giving `remote.getCurrentWindow().webContents` instead of `remote.getCurrentWebContents()` but it'll search the whole app.

```javascript
// in the webview
new FindInPage(remote.getCurrentWindow().webContents);
```

Maybe there is another workaround.
