### ISSUE TITLE
How to use the code properly in the main and renderer processes?

### ISSUE THREAD

**Issue by Yanqi-Xu** [TheoXiong/electron-find#4]
Hi Theo, thanks for this! I am totally new to electron and was trying to configure the main.js and index.js that was generated from a webpage(I am using Notion).
I tried to insert the code snippet to the main.js, but nothing really showed up and then I tried the accelerator method, and it didn't work either. 
```
accelerator:'CmdOrCtrl+F',
      function () {
        mainWindow.webContents.send('on-find', '')
```
Hope you could help! Thanks!
我是一个自学代码的记者，对electron还不怎么了解，查了一些资料还是没能自己弄明白。我用了一个把Web APP变成electron desktop app的工具，所以它本身就已经有不少globalshortcuts, 如果能请你多指点一下这些代码应该放在JS中的什么位置，文件路径是否有关联，变量名字是否有需要改变，多谢！

**Comment by TheoXiong** [comment]
你好，感谢你的关注。
我猜你应该是想把‘CmdOrCtrl+F’快捷键注册到Electron App的菜单项里面去吧，可以这样实现：
 ```
    {
        label: 'Find',
        accelerator: 'CmdOrCtrl+F',
        click: function (item, focusedWindow) {
           if (focusedWindow) { focusedWindow.webContents.send('on-find', '') }
        }
    }
```
click对应的方法就是点击菜单栏--Find菜单项（或者执行快捷键CmdOrCtrl+F）时所执行的回调。

由于我没有看到你的完整代码，以上也是根据你提供的代码片段来初步判断的，你可以根据这个试试，如果还有问题，也可以通过这个邮箱联系我：theoxiong@outlook.com

以下是一个菜单栏设置的简单实例：
```
const { Menu } = require('electron')

let template = [
  {
    label: 'Edit',
    submenu: [
      {
        label: 'Undo',
        accelerator: 'CmdOrCtrl+Z',
        role: 'undo'
      },
      {
        label: 'Redo',
        accelerator: 'Shift+CmdOrCtrl+Z',
        role: 'redo'
      },
      {
        label: 'Copy',
        accelerator: 'CmdOrCtrl+C',
        role: 'copy'
      }
    ]
  },
  {
    label: 'View',
    submenu: [
      {
        label: 'Find',
        accelerator: 'CmdOrCtrl+F',
        click: function (item, focusedWindow) {
          if (focusedWindow) { focusedWindow.webContents.send('on-find', '') }
        }
      },
      {
        label: 'Reload',
        accelerator: 'CmdOrCtrl+R',
        click: function (item, focusedWindow) {
          if (focusedWindow) { focusedWindow.reload() }
        }
      } 
    ]
  },
]

let menu = Menu.buildFromTemplate(template)
Menu.setApplicationMenu(menu)

```

**Comment by TheoXiong** [comment]
[https://electronjs.org/docs/api/menu](https://electronjs.org/docs/api/menu)
这个是electron api文档，希望能够对你有所帮助。
